// Package file
// File:        extension.go
// Url:         https://github.com/xiang-tai-duo/go-bootstrap/blob/master/file/extension.go
// Author:      TRAE.AI
// Created:     2025/12/20 12:31:58
// Description: File provides common file extension constants
// --------------------------------------------------------------------------------
package file

//goland:noinspection GoNameStartsWithPackageName,SpellCheckingInspection,GoSnakeCaseUsage
type (
	FILE_EXTENSION struct {
		AAC        string
		ACCDB      string
		ADOC       string
		AI         string
		ALAC       string
		APK        string
		APP        string
		AVI        string
		BAK        string
		BAT        string
		BMP        string
		BZ2        string
		C          string
		CFG        string
		CER        string
		CMD        string
		CONF       string
		CRT        string
		CPP        string
		CS         string
		CSV        string
		CSS        string
		DB         string
		DEB        string
		DLL        string
		DOC        string
		DOCX       string
		DOT        string
		DYLIB      string
		ENV        string
		ENV_LOCAL  string
		EXE        string
		E_3GP      string
		E_7Z       string
		FLAC       string
		FLV        string
		GIF        string
		GO         string
		GZ         string
		H          string
		HPP        string
		HTM        string
		HTML       string
		ICO        string
		INI        string
		ISO        string
		JAVA       string
		JKS        string
		JPEG       string
		JPG        string
		JS         string
		JSON       string
		KEY        string
		KT         string
		LOG        string
		M4A        string
		MARKDOWN   string
		MD         string
		MDB        string
		MKV        string
		MOV        string
		MP3        string
		MP4        string
		MPEG       string
		MPG        string
		MSI        string
		ODP        string
		ODS        string
		ODT        string
		OGG        string
		P12        string
		PDF        string
		PEM        string
		PFX        string
		PHP        string
		PNG        string
		PPT        string
		PPTX       string
		PROP       string
		PROPERTIES string
		PS1        string
		PSD        string
		PY         string
		RAW        string
		RB         string
		RAR        string
		RPM        string
		RS         string
		RST        string
		RTF        string
		SCALA      string
		SH         string
		SO         string
		SQL        string
		SQLITE     string
		SVG        string
		SWAP       string
		SWIFT      string
		SWP        string
		TAR        string
		TEMP       string
		TGZ        string
		TIF        string
		TIFF       string
		TMP        string
		TS         string
		TXT        string
		WAV        string
		WEBM       string
		WEBP       string
		WMV        string
		WMA        string
		XLS        string
		XLSX       string
		XML        string
		XZ         string
		YAML       string
		YML        string
		Z          string
		ZIP        string
	}
)

//goland:noinspection GoUnusedGlobalVariable
var (
	Extensions = FILE_EXTENSION{
		AAC:        ".aac",
		ACCDB:      ".accdb",
		ADOC:       ".adoc",
		AI:         ".ai",
		ALAC:       ".alac",
		APK:        ".apk",
		APP:        ".app",
		AVI:        ".avi",
		BAK:        ".bak",
		BAT:        ".bat",
		BMP:        ".bmp",
		BZ2:        ".bz2",
		C:          ".c",
		CFG:        ".cfg",
		CER:        ".cer",
		CMD:        ".cmd",
		CONF:       ".conf",
		CRT:        ".crt",
		CPP:        ".cpp",
		CS:         ".cs",
		CSV:        ".csv",
		CSS:        ".css",
		DB:         ".db",
		DEB:        ".deb",
		DLL:        ".dll",
		DOC:        ".doc",
		DOCX:       ".docx",
		DOT:        ".",
		DYLIB:      ".dylib",
		ENV:        ".env",
		ENV_LOCAL:  ".env.local",
		EXE:        ".exe",
		E_3GP:      ".3gp",
		E_7Z:       ".7z",
		FLAC:       ".flac",
		FLV:        ".flv",
		GIF:        ".gif",
		GO:         ".go",
		GZ:         ".gz",
		H:          ".h",
		HPP:        ".hpp",
		HTM:        ".htm",
		HTML:       ".html",
		ICO:        ".ico",
		INI:        ".ini",
		ISO:        ".iso",
		JAVA:       ".java",
		JKS:        ".jks",
		JPEG:       ".jpeg",
		JPG:        ".jpg",
		JS:         ".js",
		JSON:       ".json",
		KEY:        ".key",
		KT:         ".kt",
		LOG:        ".log",
		M4A:        ".m4a",
		MARKDOWN:   ".markdown",
		MD:         ".md",
		MDB:        ".mdb",
		MKV:        ".mkv",
		MOV:        ".mov",
		MP3:        ".mp3",
		MP4:        ".mp4",
		MPEG:       ".mpeg",
		MPG:        ".mpg",
		MSI:        ".msi",
		ODP:        ".odp",
		ODS:        ".ods",
		ODT:        ".odt",
		OGG:        ".ogg",
		P12:        ".p12",
		PDF:        ".pdf",
		PEM:        ".pem",
		PFX:        ".pfx",
		PHP:        ".php",
		PNG:        ".png",
		PPT:        ".ppt",
		PPTX:       ".pptx",
		PROP:       ".prop",
		PROPERTIES: ".properties",
		PS1:        ".ps1",
		PSD:        ".psd",
		PY:         ".py",
		RAW:        ".raw",
		RB:         ".rb",
		RAR:        ".rar",
		RPM:        ".rpm",
		RS:         ".rs",
		RST:        ".rst",
		RTF:        ".rtf",
		SCALA:      ".scala",
		SH:         ".sh",
		SO:         ".so",
		SQL:        ".sql",
		SQLITE:     ".sqlite",
		SVG:        ".svg",
		SWAP:       ".swap",
		SWIFT:      ".swift",
		SWP:        ".swp",
		TAR:        ".tar",
		TEMP:       ".temp",
		TGZ:        ".tgz",
		TIF:        ".tif",
		TIFF:       ".tiff",
		TMP:        ".tmp",
		TS:         ".ts",
		TXT:        ".txt",
		WAV:        ".wav",
		WEBM:       ".webm",
		WEBP:       ".webp",
		WMV:        ".wmv",
		WMA:        ".wma",
		XLS:        ".xls",
		XLSX:       ".xlsx",
		XML:        ".xml",
		XZ:         ".xz",
		YAML:       ".yaml",
		YML:        ".yml",
		Z:          ".z",
		ZIP:        ".zip",
	}
)
